### ISSUE TITLE
CreatePodHttpClient_IntegrationTest_Async is flakey

### ISSUE THREAD

**Issue by qmfrederik** [kaponata-io/kaponata#118]
```
[xUnit.net 00:00:19.94]     Kaponata.Kubernetes.Tests.KubernetesClientIntegrationTests.CreatePodHttpClient_IntegrationTest_Async [FAIL]
  Failed Kaponata.Kubernetes.Tests.KubernetesClientIntegrationTests.CreatePodHttpClient_IntegrationTest_Async [15 s]
  Error Message:
   System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : error forwarding port 80 to pod 34d1f5d2189dcb89221f4fb4d2006c2c35e3a0f9d6965845d5391f6a65e8727d, uid : failed to execute portforward in network namespace "/var/run/netns/cni-7dcd776d-b931-31e8-ab18-8186c80e1036": failed to dial 80: dial tcp4 127.0.0.1:80: connect: connection refused
  Stack Trace:
     at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Kaponata.Kubernetes.Tests.KubernetesClientIntegrationTests.CreatePodHttpClient_IntegrationTest_Async() in /home/runner/work/kaponata/kaponata/src/Kaponata.Kubernetes.Tests/KubernetesClientIntegrationTests.cs:line 128
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Kaponata.Kubernetes.PortForwardStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /home/runner/work/kaponata/kaponata/src/Kaponata.Kubernetes/PortForwardStream.cs:line 134
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  Standard Output Messages:
 Debug [0]: Got an Modified event for a V1Pod object
 Debug [0]: Got an Modified event for a V1Pod object
 Debug [0]: Got an Modified event for a V1Pod object
 Information [0]: Stopped watching 'V1Pod' objects because the client requested to stop watching.
 Information [0]: Connecting to port k8s.Models.V1Pod on pod createpodhttpclient-integrationtest-async
 Information [0]: Connected to port 80 on pod createpodhttpclient-integrationtest-async
 Information [0]: Initializing stream. Reading first packets.
 Information [0]: Initializing stream: read value 80 on stream 0.
 Information [0]: Initializing stream: read value 80 on stream 1.
 Information [0]: Successfully intialized stream.
 Information [0]: Got data on stream 1.
```

**Comment by qmfrederik** [comment]
Probably mitigated/fixed by e3f9085c0eb81583e7e4fb1e663e10932eb66366
